const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.PREVIEW_URL || 'http://127.0.0.1:8080/Multi-Stopwatch/';
(async () => {
  fs.mkdirSync('test-results/visual', { recursive: true });
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, colorScheme: 'light' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(String(e)));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto(base);
  await page.getByText('オフラインで利用できます', { exact: true }).waitFor();
  await page.getByRole('button', { name: /新しい計測/ }).click();
  await page.locator('[name=name]').fill('資格の勉強');
  await page.locator('[name=memo]').fill('今日の積み重ね');
  await page.locator('[name=targetH]').fill('20');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByRole('button', { name: '資格の勉強を開始' }).click();
  await page.locator('.time .sr-only').filter({ hasNotText: '0時間0分0秒' }).waitFor({ timeout: 3000 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: 'test-results/visual/mobile-light.png', fullPage: true });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.screenshot({ path: 'test-results/visual/mobile-dark.png', fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.screenshot({ path: 'test-results/visual/desktop.png', fullPage: true });
  await page.reload();
  await page.getByRole('button', { name: '資格の勉強を停止' }).waitFor();
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('button', { name: '資格の勉強を停止' }).click();
  assert.equal(await page.locator('.state-text').textContent(), '停止中');
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: mobile/desktop, light/dark, create/start/reload/offline/stop, no overflow or browser errors');
})().catch(error => { console.error(error); process.exit(1); });
